// <auto-generated />
using System;
using BlazorTest.ServerSide.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorTest.ServerSide.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220717134017_Add kanji comparison")]
    partial class Addkanjicomparison
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4");

            modelBuilder.Entity("BlazorTest.ServerSide.Models.Kanji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Meanings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kanji");
                });
#pragma warning restore 612, 618
        }
    }
}
